// admin.js - administra localStorage data
const STORAGE_KEY='mi_tienda_data';
function getStore(){ const s=localStorage.getItem(STORAGE_KEY); return s?JSON.parse(s):null; }
function setStore(obj){ localStorage.setItem(STORAGE_KEY, JSON.stringify(obj)); }
async function initAdmin(){ if(!getStore()){ try{ const r=await fetch('data.json'); const j=await r.json(); setStore(j); }catch(e){ setStore({ categorias:['Baterías','Cargadores','Módulos','Placas de Carga','Tapas Traseras'], productos:[], banners:[], redes:{} }); } } renderAll(); }
function renderAll(){ const s=getStore(); renderCategoriasList(s.categorias||[]); renderCategoriasSelect(s.categorias||[]); renderProductosList(s.productos||[]); renderBannersList(s.banners||[]); fillRedesForm(s.redes||{}); }
function renderCategoriasList(cats){ const ul=document.getElementById('lista-categorias'); ul.innerHTML=''; cats.forEach((c,i)=>{ const li=document.createElement('li'); li.textContent=c+' '; const del=document.createElement('button'); del.textContent='Eliminar'; del.onclick=()=>{ if(confirm('Eliminar categoria y sus productos?')) removeCategory(c); }; li.appendChild(del); ul.appendChild(li); }); }
function renderCategoriasSelect(cats){ const sel=document.getElementById('categoria'); sel.innerHTML=''; cats.forEach(c=>{ const opt=document.createElement('option'); opt.value=c; opt.textContent=c; sel.appendChild(opt); }); }
function renderProductosList(products){ const cont=document.getElementById('lista-productos'); cont.innerHTML=''; products.forEach((p,i)=>{ const div=document.createElement('div'); div.className='item'; div.innerHTML=`<strong>${p.nombre}</strong> - ${p.categoria} - $${Number(p.precio).toFixed(2)}`; const del=document.createElement('button'); del.textContent='Eliminar'; del.onclick=()=>{ if(confirm('Eliminar producto?')) deleteProduct(i); }; div.appendChild(del); cont.appendChild(div); }); }
function renderBannersList(banners){ const cont=document.getElementById('lista-banners'); cont.innerHTML=''; banners.forEach((b,i)=>{ const div=document.createElement('div'); const img=document.createElement('img'); img.src=b.src; img.style.height='60px'; img.style.objectFit='cover'; img.style.marginRight='8px'; const txt=document.createElement('div'); txt.textContent=b.cat?('Filtra: '+b.cat):'Sin cat'; const del=document.createElement('button'); del.textContent='Eliminar'; del.onclick=()=>{ if(confirm('Eliminar banner?')) deleteBanner(i); }; div.appendChild(img); div.appendChild(txt); div.appendChild(del); cont.appendChild(div); }); }
function fillRedesForm(r){ document.getElementById('facebook').value=r.facebook||''; document.getElementById('instagram').value=r.instagram||''; document.getElementById('tiktok').value=r.tiktok||''; document.getElementById('youtube').value=r.youtube||''; document.getElementById('whatsapp').value=r.whatsapp||''; }
document.getElementById('form-categoria').addEventListener('submit', function(e){ e.preventDefault(); const name=document.getElementById('nueva-categoria').value.trim(); if(!name) return alert('Nombre vacío'); const s=getStore(); s.categorias=s.categorias||[]; if(s.categorias.includes(name)) return alert('Ya existe'); s.categorias.push(name); setStore(s); renderAll(); this.reset(); });
document.getElementById('form-producto').addEventListener('submit', async function(e){ e.preventDefault(); const nombre=document.getElementById('nombre').value.trim(); const descripcion=document.getElementById('descripcion').value.trim(); const precio=Number(document.getElementById('precio').value||0); const categoria=document.getElementById('categoria').value; const file=document.getElementById('imagen-file').files[0]; let img=''; if(file) img=await readFileAsDataURL(file); const s=getStore(); s.productos=s.productos||[]; s.productos.push({ nombre, descripcion, precio, categoria, imagen: img }); setStore(s); renderAll(); this.reset(); });
document.getElementById('form-banner').addEventListener('submit', async function(e){ e.preventDefault(); const file=document.getElementById('banner-file').files[0]; const cat=document.getElementById('banner-cat').value.trim(); if(!file) return alert('Elegí una imagen'); const src=await readFileAsDataURL(file); const s=getStore(); s.banners=s.banners||[]; s.banners.push({ src, cat: cat||'' }); setStore(s); renderAll(); this.reset(); });
document.getElementById('form-redes').addEventListener('submit', function(e){ e.preventDefault(); const s=getStore(); s.redes={ facebook:document.getElementById('facebook').value.trim(), instagram:document.getElementById('instagram').value.trim(), tiktok:document.getElementById('tiktok').value.trim(), youtube:document.getElementById('youtube').value.trim(), whatsapp:document.getElementById('whatsapp').value.trim() }; setStore(s); alert('Redes guardadas'); renderAll(); });
function readFileAsDataURL(file){ return new Promise((res,rej)=>{ const r=new FileReader(); r.onload=()=>res(r.result); r.onerror=rej; r.readAsDataURL(file); }); }
function deleteProduct(idx){ const s=getStore(); s.productos.splice(idx,1); setStore(s); renderAll(); }
function deleteBanner(idx){ const s=getStore(); s.banners.splice(idx,1); setStore(s); renderAll(); }
function removeCategory(name){ const s=getStore(); s.categorias=s.categorias.filter(c=>c!==name); s.productos=(s.productos||[]).filter(p=>p.categoria!==name); setStore(s); renderAll(); }
document.getElementById('exportBtn').addEventListener('click', ()=>{ const s=getStore(); const blob=new Blob([JSON.stringify(s,null,2)], {type:'application/json'}); const url=URL.createObjectURL(blob); const a=document.createElement('a'); a.href=url; a.download='mi_tienda_export.json'; a.click(); URL.revokeObjectURL(url); });
initAdmin();
