function loadData(){ let ds = localStorage.getItem('mi_tienda_data'); if(!ds){ fetch('data.json').then(r=>r.json()).then(j=>{ localStorage.setItem('mi_tienda_data', JSON.stringify(j)); renderAll(j); }).catch(e=>{ console.error('No seed', e); renderAll({ categorias:[], productos:[], banners:[], redes:{} }); }); } else { renderAll(JSON.parse(ds)); } }
function renderAll(data){ renderMenuCats(data.categorias||[]); renderSidebarCats(data.categorias||[]); renderProducts(data.productos||[]); renderBanners(data.banners||[]); renderSocials(data.redes||{}); setupSearch(); document.getElementById('site-year').textContent=new Date().getFullYear(); }
function renderMenuCats(cats){ const menu = document.getElementById('menu-categorias'); menu.innerHTML=''; const all=document.createElement('a'); all.href='#'; all.textContent='Todas'; all.onclick=(e)=>{e.preventDefault(); renderProductsFromStore(); document.getElementById('titulo-categoria').textContent='Todos los productos';}; menu.appendChild(all); cats.forEach(c=>{ const a=document.createElement('a'); a.href='#'; a.textContent=c; a.onclick=(ev)=>{ev.preventDefault(); filterByCategory(c); document.getElementById('titulo-categoria').textContent=c; }; menu.appendChild(a); }); }
function renderSidebarCats(cats){ const ul=document.getElementById('sidebar-cats'); ul.innerHTML=''; cats.forEach(c=>{ const li=document.createElement('li'); li.innerHTML=`<a href="#" data-cat="${c}">${c}</a>`; li.querySelector('a').onclick=(ev)=>{ev.preventDefault(); filterByCategory(c); document.getElementById('titulo-categoria').textContent=c; window.scrollTo({top:document.getElementById('productos').offsetTop-80, behavior:'smooth'}); }; ul.appendChild(li); }); }
function renderProducts(products){ const prods = Array.isArray(products)?products:(products.productos||[]); const cont=document.getElementById('productos'); cont.innerHTML=''; prods.forEach(p=>{ const div=document.createElement('div'); div.className='producto'; const img=document.createElement('img'); img.src=p.imagen||'assets/placeholder.png'; const h3=document.createElement('h3'); h3.textContent=p.nombre; const pdesc=document.createElement('p'); pdesc.textContent=p.descripcion||''; const price=document.createElement('div'); price.style.fontWeight='600'; price.textContent='$ '+Number(p.precio).toLocaleString('es-AR',{minimumFractionDigits:2}); div.appendChild(img); div.appendChild(h3); div.appendChild(pdesc); div.appendChild(price); cont.appendChild(div); }); if(prods.length===0) cont.innerHTML='<div class="small">No hay productos para mostrar.</div>'; }
function renderBanners(banners){ const sec=document.getElementById('banner'); sec.innerHTML=''; if(!banners||banners.length===0){ sec.textContent='Subí banners desde el admin'; return; } banners.forEach((b,idx)=>{ const img=document.createElement('img'); img.src=b.src; img.dataset.cat=b.cat||''; img.style.cursor='pointer'; img.onclick=()=>{ if(b.cat){ filterByCategory(b.cat); document.getElementById('titulo-categoria').textContent=b.cat; } window.scrollTo({top:document.getElementById('productos').offsetTop-60, behavior:'smooth'}); }; img.style.display=idx===0?'block':'none'; sec.appendChild(img); }); let i=0; setInterval(()=>{ const imgs=sec.querySelectorAll('img'); if(imgs.length<=1) return; imgs[i].style.display='none'; i=(i+1)%imgs.length; imgs[i].style.display='block'; },4000); }
function renderSocials(redes){ const cont=document.getElementById('social-links'); const footer=document.getElementById('footer-social'); cont.innerHTML=''; footer.innerHTML=''; ['facebook','instagram','tiktok','youtube'].forEach(k=>{ if(redes[k]){ const a=document.createElement('a'); a.href=redes[k]; a.target='_blank'; a.textContent=k; a.style.margin='0 6px'; cont.appendChild(a); footer.appendChild(a.cloneNode(true)); } }); if(redes.whatsapp){ document.getElementById('whatsapp-btn').href='https://wa.me/'+redes.whatsapp; document.getElementById('whatsapp-btn').style.display='flex'; } else document.getElementById('whatsapp-btn').style.display='none'; }
function readStore(){ return JSON.parse(localStorage.getItem('mi_tienda_data')||'{}'); }
function renderProductsFromStore(){ const s=readStore(); renderProducts(s.productos||[]); }
function filterByCategory(cat){ const s=readStore(); const prods=(s.productos||[]).filter(p=>p.categoria===cat); renderProducts(prods); }
function setupSearch(){ const q=document.getElementById('q'); q.oninput=()=>{ const val=q.value.toLowerCase(); const s=readStore(); const prods=(s.productos||[]).filter(p=>(p.nombre||'').toLowerCase().includes(val)||(p.descripcion||'').toLowerCase().includes(val)); renderProducts(prods); }; }
window.addEventListener('DOMContentLoaded', loadData);
